### ISSUE TITLE
Is there a tutorial?

### ISSUE THREAD

**Issue by cluelessdude** [ohyou/twitch-viewer#22]
I have never used python on windows so i downloaded python 2.7.10 for windows. When i ran it through CMD first i got a "no module named requests" error. So installed it through pip. Now i am getting no module named urllib3. I was wondering what i am doing wrong. Cause urllib3 is in the python 2.7 folder but i cant seem to start it.

**Comment by RocksteadyOnNirvana** [comment]
That's happening (I guess, this is the first time that I'm using python too), because you didn't installed the packages.
You will need install: json, livestreamer and request packages through "pip" (A package manager).
On windows, open cmd, give path as cd and path to the "Scripts" (At Python folder) and use the command install.
It will be like:
`E:\python27\scripts\>pip install requests `
`E:\python27\scripts\>pip install json`
`E:\python27\scripts\>pip install livestreamer`

and you can do the same thing to install urllib3.

After this you need open your file, open cmd and cd you twitch-viewer-master folder.
You will open it like this:
`E:\twitch-viewer-master>twitch-viewer.py {streamname}`

I hope I could help. Sorry for my bad english.
Good luck.

**Comment by knifemotion** [comment]
@RocksteadyOnNirvana for some reason i can't download json `Command "python setup.py egg_info" failed with error code 1 in c:\users\test\app
data\local\temp\pip-build-jyczlb\json\`

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
